INSERT INTO books (title, author, category, price_cents, description, cover_url)
VALUES
  ('1984', 'George Orwell', 'Dystopian Fiction', 1499,
   'A chilling story about surveillance, control, and truth.', NULL),
  ('To Kill a Mockingbird', 'Harper Lee', 'Classic / Historical Fiction', 1599,
   'A powerful classic about justice and compassion in the American South.', NULL),
  ('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic / Tragedy', 1299,
   'A tragic tale of wealth, love, and the American Dream.', NULL),
  ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 1799,
   'A young wizard discovers a world of magic and friendship.', NULL),
  ('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 2499,
   'An epic journey to destroy a powerful ring and save Middle-earth.', NULL),
  ('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 1599,
   'Bilbo Baggins sets out on an unexpected adventure.', NULL),
  ('Pride and Prejudice', 'Jane Austen', 'Romance / Classic', 1299,
   'A witty romance about manners, misunderstanding, and love.', NULL),
  ('The Catcher in the Rye', 'J.D. Salinger', 'Coming-of-age Fiction', 1399,
   'A teenager’s candid narration of alienation and growing up.', NULL),
  ('The Hunger Games', 'Suzanne Collins', 'Dystopian / Sci-Fi', 1699,
   'A deadly televised competition sparks rebellion.', NULL),
  ('Brave New World', 'Aldous Huxley', 'Dystopian / Sci-Fi', 1499,
   'A futuristic society built on control, pleasure, and conditioning.', NULL),
  ('The Diary of a Young Girl', 'Anne Frank', 'Biography / Memoir', 1499,
   'Anne Frank’s moving diary written during World War II.', NULL),
  ('Long Walk to Freedom', 'Nelson Mandela', 'Autobiography', 1999,
   'Mandela’s autobiography about resilience and justice.', NULL),
  ('Steve Jobs', 'Walter Isaacson', 'Biography', 1999,
   'A biography of Apple co-founder Steve Jobs.', NULL),
  ('Becoming', 'Michelle Obama', 'Memoir', 1899,
   'Michelle Obama’s personal story and journey.', NULL),
  ('The Wright Brothers', 'David McCullough', 'Biography', 1799,
   'The inspiring story of the brothers who invented flight.', NULL),
  ('Educated', 'Tara Westover', 'Memoir', 1799,
   'A memoir about family, education, and transformation.', NULL),
  ('I Am Malala', 'Malala Yousafzai', 'Biography / Memoir', 1699,
   'The story of Malala and the fight for education.', NULL),
  ('The Glass Castle', 'Jeannette Walls', 'Memoir', 1599,
   'A memoir of a childhood shaped by poverty and resilience.', NULL),
  ('Born a Crime', 'Trevor Noah', 'Memoir / Humor', 1699,
   'A funny and moving memoir about growing up in South Africa.', NULL),
  ('When Breath Becomes Air', 'Paul Kalanithi', 'Memoir', 1599,
   'A reflection on life, death, and meaning by a neurosurgeon.', NULL),
  ('Dune', 'Frank Herbert', 'Science Fiction', 1899,
   'A sci-fi epic of politics, prophecy, and survival on Arrakis.', NULL),
  ('Foundation', 'Isaac Asimov', 'Science Fiction', 1699,
   'A classic saga about preserving knowledge in a collapsing empire.', NULL),
  ('Ender''s Game', 'Orson Scott Card', 'Science Fiction', 1699,
   'A gifted child is trained to defend humanity in space war.', NULL),
  ('The Martian', 'Andy Weir', 'Science Fiction', 1799,
   'An astronaut uses science and humor to survive on Mars.', NULL),
  ('Neuromancer', 'William Gibson', 'Cyberpunk / Sci-Fi', 1599,
   'A cyberpunk classic that helped define the genre.', NULL),
  ('Snow Crash', 'Neal Stephenson', 'Cyberpunk / Sci-Fi', 1699,
   'A fast-paced cyberpunk adventure in a hyper-connected world.', NULL),
  ('Ready Player One', 'Ernest Cline', 'Sci-Fi / Adventure', 1599,
   'A virtual reality treasure hunt packed with pop culture.', NULL),
  ('The Time Machine', 'H.G. Wells', 'Sci-Fi / Classic', 1199,
   'A classic story of time travel and the future of humanity.', NULL),
  ('Frankenstein', 'Mary Shelley', 'Sci-Fi / Gothic', 1199,
   'A foundational gothic tale about creation and responsibility.', NULL),
  ('Jurassic Park', 'Michael Crichton', 'Sci-Fi / Thriller', 1699,
   'A techno-thriller where resurrected dinosaurs go wrong.', NULL),
  ('The Da Vinci Code', 'Dan Brown', 'Mystery / Thriller', 1599,
   'A fast-paced mystery involving secrets, symbols, and history.', NULL),
  ('Gone Girl', 'Gillian Flynn', 'Thriller / Mystery', 1599,
   'A twisty thriller about a marriage and a disappearance.', NULL),
  ('Sherlock Holmes: A Study in Scarlet', 'Arthur Conan Doyle', 'Mystery / Detective', 1099,
   'The first Sherlock Holmes mystery and introduction to Watson.', NULL),
  ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Crime / Thriller', 1699,
   'A dark mystery involving a missing person and hidden crimes.', NULL),
  ('Big Little Lies', 'Liane Moriarty', 'Mystery / Drama', 1599,
   'Secrets and drama build to a shocking event.', NULL),
  ('In the Woods', 'Tana French', 'Crime / Mystery', 1599,
   'A detective novel with psychological depth and suspense.', NULL),
  ('The Silent Patient', 'Alex Michaelides', 'Psychological Thriller', 1699,
   'A therapist tries to uncover why a patient stopped speaking.', NULL),
  ('And Then There Were None', 'Agatha Christie', 'Mystery', 1299,
   'A classic mystery where guests are eliminated one by one.', NULL),
  ('The Woman in the Window', 'A.J. Finn', 'Thriller', 1599,
   'A psychological thriller about what was (or wasn’t) seen.', NULL),
  ('The Reversal', 'Michael Connelly', 'Legal Thriller', 1499,
   'A legal thriller involving a high-profile reversal case.', NULL),
  ('The Alchemist', 'Paulo Coelho', 'Philosophical Fiction', 1399,
   'A story about purpose, destiny, and following your dream.', NULL),
  ('Life of Pi', 'Yann Martel', 'Adventure / Philosophical Fiction', 1499,
   'A survival story with philosophical and spiritual themes.', NULL),
  ('The Kite Runner', 'Khaled Hosseini', 'Historical Fiction / Drama', 1599,
   'A powerful novel about friendship, guilt, and redemption.', NULL),
  ('A Thousand Splendid Suns', 'Khaled Hosseini', 'Historical Fiction', 1599,
   'A moving story of love and resilience across generations.', NULL),
  ('The Book Thief', 'Markus Zusak', 'Historical Fiction', 1499,
   'A WWII story narrated by Death, centered on books and hope.', NULL),
  ('The Road', 'Cormac McCarthy', 'Post-Apocalyptic Fiction', 1499,
   'A stark journey of survival between father and son.', NULL),
  ('The Fault in Our Stars', 'John Green', 'Romance / Drama', 1499,
   'A heartfelt romance about two teens facing illness.', NULL),
  ('Me Before You', 'Jojo Moyes', 'Romance / Drama', 1499,
   'A romance that explores love, choice, and change.', NULL),
  ('The Help', 'Kathryn Stockett', 'Historical Fiction', 1599,
   'A story of courage and friendship in 1960s Mississippi.', NULL),
  ('Where the Crawdads Sing', 'Delia Owens', 'Mystery / Drama', 1699,
   'A mystery and coming-of-age story set in the marshes.', NULL);

